// <auto-generated />
namespace brownshouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edit_subactivity_number : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_subactivity_number));
        
        string IMigrationMetadata.Id
        {
            get { return "201807051125143_edit_subactivity_number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
