// <auto-generated />
namespace brownshouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_users_to_requests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_users_to_requests));
        
        string IMigrationMetadata.Id
        {
            get { return "201805310823027_add_users_to_requests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
