// <auto-generated />
namespace brownshouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_programMail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_programMail));
        
        string IMigrationMetadata.Id
        {
            get { return "201807051313104_add_programMail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
