// <auto-generated />
namespace brownshouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class set_null_acceptances : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_null_acceptances));
        
        string IMigrationMetadata.Id
        {
            get { return "201805230946597_set_null_acceptances"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
